#!/usr/bin/env python3
"""
Step1X-3D Offline 3D Mesh and Texture Generation Pipeline
==========================================================

This script drives a fully **offline**, server-local execution of the
Step1X-3D two-stage 3D generation pipeline for anime IP merchandise
supervision.  It takes a cleaned, white-background reference image of
a character (plus a foreground silhouette mask) and produces:

Stage 1 - Geometry
    A watertight 3D mesh in GLB format extracted from a neural occupancy
    field, generated by the Step1X-3D-Geometry-1300m diffusion model.

Stage 2 - Texture
    A fully textured version of the geometry GLB, produced by the
    Step1X-3D-Texture pipeline (SDXL-based image-guided multi-view
    diffusion with IP-Adapter-XL / IG2MV).

Both stages write a JSON manifest recording input hashes, model
revisions, and all generation settings so that results are fully
reproducible and traceable back to a specific source image.

Inputs required
---------------
- A cleaned white-background PNG of the character front view
  (typically ``cleaned_white.png`` from the local pipeline).
- A binary/greyscale foreground mask PNG that isolates the character
  from the background (typically ``foreground_mask.png``).
- All model weights present at the server-local paths defined by the
  module-level constants (Step1X-3D-Geometry, Step1X-3D-Texture,
  SDXL-base-1.0, sdxl-vae-fp16-fix).

Outputs produced
----------------
``<output_dir>/char_001_geometry.glb``
    Raw geometry mesh from Stage 1.
``<output_dir>/char_001_textured.glb``
    Textured mesh from Stage 2.
``<output_dir>/char_001_transparent_input.png``
    The RGBA composite used as the geometry stage input (source + mask).
``<output_dir>/texture_intermediates/``
    Per-iteration view renders saved by the texture pipeline.
``<output_dir>/manifest.json``
    Full provenance record: timestamps, SHA-256 digests, model paths,
    and all generation settings.

Conda environment
-----------------
Run this script inside the ``step1x3d`` conda environment on the
inference server::

    conda activate step1x3d
    python generate_local_step1x3d.py [--stage geometry|texture|all]

The environment must have PyTorch >= 2.2, diffusers, transformers,
trimesh, Pillow, and the Step1X-3D source tree on ``sys.path``
(handled automatically via the ``STEP1X_CODE`` constant below).

Network policy
--------------
All Hugging Face hub calls are forced offline via environment variables
set at import time, ensuring no accidental model downloads on the
air-gapped inference server.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image


# ---------------------------------------------------------------------------
# Offline mode: disable all Hugging Face network access before any HF import.
# These must be set before ``transformers`` or ``diffusers`` is imported so
# that their hub clients are instantiated in offline mode.
# ---------------------------------------------------------------------------
os.environ.setdefault("HF_HUB_OFFLINE", "1")           # Block hub downloads
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")      # Block transformers hub
os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY", "1")  # No usage pings

# ---------------------------------------------------------------------------
# Server-local path constants.
# All model weights live on the inference server's local filesystem.
# Changing these requires a corresponding model deployment step.
# ---------------------------------------------------------------------------

# Root of the 2D-to-3D supervision project on the inference server.
PROJECT_ROOT = Path("/home/intern/Supervised 2D to 3D")

# Directory where the Step1X-3D GitHub repository has been cloned.
# Added to sys.path at runtime so its Python packages are importable.
STEP1X_CODE = Path("/home/intern/liuhongliang/Step1X-3D")

# Specific HuggingFace snapshot revision of the Step1X-3D model weights.
# Pinning to a snapshot hash guarantees reproducibility across server restarts.
STEP1X_MODEL = Path(
    "/home/intern/.cache/huggingface/hub/"
    "models--stepfun-ai--Step1X-3D/snapshots/"
    "bf7084495b3a72222f36549b7942948aa4d9daa7"
)

# SDXL base model used by the texture pipeline as the backbone U-Net.
SDXL_MODEL = Path("/home/intern/local-ai-models/comfyui/diffusers/sdxl-base-1.0")

# Pinned snapshot of the fp16-safe SDXL VAE (fixes numeric instability in the
# standard SDXL VAE at float16 precision).
SDXL_VAE = Path(
    "/home/intern/.cache/huggingface/hub/"
    "models--madebyollin--sdxl-vae-fp16-fix/snapshots/"
    "207b116dae70ace3637169f1ddd2434b91b3a8cd"
)

# Default input paths for the char_001 reference asset.
DEFAULT_SOURCE = Path(
    "/home/intern/wmy/ComfyUI/input/local_pipeline/char_001/cleaned_white.png"
)
DEFAULT_MASK = Path(
    "/home/intern/wmy/ComfyUI/input/local_pipeline/char_001/foreground_mask.png"
)

# Default output directory for this round of candidates.
DEFAULT_OUTPUT_DIR = (
    PROJECT_ROOT
    / "vlm/experiments/comfyui_output/front_view_local/char_001/candidates/"
    "char_001_step1x3d_round1"
)


def parse_args() -> argparse.Namespace:
    """Parse and return command-line arguments for the generation run.

    All arguments have sensible defaults so the script can be run with no
    flags for the standard char_001 reference workflow.  The ``--stage``
    flag allows running geometry and texture stages independently, which is
    useful when iterating on texture settings without re-generating geometry.

    Returns
    -------
    argparse.Namespace
        Parsed arguments with attributes:

        - ``source`` (Path): Cleaned white-background input image.
        - ``foreground_mask`` (Path): Binary/grey alpha mask for the subject.
        - ``output_dir`` (Path): Directory where all outputs are written.
        - ``stage`` (str): Which stage(s) to run: "geometry", "texture", "all".
        - ``geometry_steps`` (int): Number of DDIM/diffusion steps for geometry.
        - ``texture_steps`` (int): Number of diffusion steps for texture.
        - ``seed`` (int): Global RNG seed for reproducibility.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--foreground-mask", type=Path, default=DEFAULT_MASK)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--stage", choices=("geometry", "texture", "all"), default="all")
    parser.add_argument("--geometry-steps", type=int, default=30)
    parser.add_argument("--texture-steps", type=int, default=30)
    parser.add_argument("--seed", type=int, default=20260722005)
    return parser.parse_args()


def sha256(path: Path) -> str:
    """Compute the SHA-256 hex digest of a file.

    Reads the file in 1 MiB chunks to avoid loading large GLB/PNG files
    entirely into memory.  Used to generate content hashes for the manifest
    so downstream consumers can verify that outputs have not been corrupted
    or accidentally overwritten.

    Parameters
    ----------
    path : Path
        Absolute path to the file to hash.

    Returns
    -------
    str
        64-character lowercase hexadecimal SHA-256 digest.
    """
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        # Stream in 1 MiB blocks; avoids OOM for large mesh files.
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_json(path: Path, value: object) -> None:
    """Write a JSON-serialisable object to *path* atomically.

    The atomic write pattern works by writing to a uniquely-named temporary
    file in the same directory, then replacing the target with an OS-level
    rename.  This guarantees that a reader never sees a partially-written
    manifest file, even if the process is interrupted mid-write.

    Why atomic?  The manifest is the provenance record.  If the process is
    killed between the ``open()`` and the final ``flush()`` of a normal write,
    the manifest will exist on disk but contain truncated JSON - a silent
    corruption.  ``os.replace`` is an atomic filesystem operation (POSIX
    ``rename(2)``), so the manifest either contains the complete previous
    content or the complete new content, never a partial state.

    The temporary filename includes a UUID4 hex suffix to avoid collisions
    when multiple processes write to the same output directory concurrently.

    Parameters
    ----------
    path : Path
        Target JSON file path.  Parent directories are created if absent.
    value : object
        Any JSON-serialisable Python object (dict, list, str, int, ...).
    """
    # Ensure the output directory tree exists before attempting to write.
    path.parent.mkdir(parents=True, exist_ok=True)

    # Build a sibling temp path with a collision-resistant random suffix.
    temp = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")

    # Write the full JSON to the temp file, then atomically swap it into place.
    temp.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temp, path)  # POSIX rename - atomic on all supported filesystems


def validate_local_inputs(source: Path, foreground_mask: Path) -> None:
    """Verify that all required input files and model weights are present.

    Raises ``FileNotFoundError`` with a consolidated list of missing paths
    before any GPU memory is allocated, so that configuration errors fail
    fast rather than crashing mid-run after minutes of model loading.

    Checks the following:
    - User-supplied source image and foreground mask.
    - Step1X-3D-Geometry-1300m model index and diffusion weights.
    - Step1X-3D-Texture IG2MV adapter weights.
    - SDXL base model index and U-Net weights.
    - SDXL VAE fp16-fix weights.

    Parameters
    ----------
    source : Path
        Path to the cleaned white-background reference image.
    foreground_mask : Path
        Path to the foreground silhouette mask image.

    Raises
    ------
    FileNotFoundError
        If one or more required files are absent from the filesystem.
    """
    required = [
        source,
        foreground_mask,
        # Geometry model - pipeline configuration
        STEP1X_MODEL / "Step1X-3D-Geometry-1300m/model_index.json",
        # Geometry model - main transformer/diffusion weights
        STEP1X_MODEL
        / "Step1X-3D-Geometry-1300m/transformer/diffusion_pytorch_model.safetensors",
        # Texture model - IG2MV IP-Adapter weights
        STEP1X_MODEL / "Step1X-3D-Texture/step1x-3d-ig2v.safetensors",
        # SDXL backbone - pipeline configuration
        SDXL_MODEL / "model_index.json",
        # SDXL backbone - U-Net weights
        SDXL_MODEL / "unet/diffusion_pytorch_model.safetensors",
        # fp16-safe SDXL VAE weights
        SDXL_VAE / "diffusion_pytorch_model.safetensors",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise FileNotFoundError("Incomplete server-local inputs:\n" + "\n".join(missing))


def main() -> None:
    """Entry point: run geometry and/or texture generation for a single asset.

    Execution flow
    --------------
    1. Parse arguments and validate that all local files are present.
    2. Composite the cleaned source image with the foreground mask to produce
       an RGBA PNG; this transparent image is used as the geometry stage input
       because the Step1X-3D geometry pipeline expects an RGBA image with the
       subject on a transparent background.
    3. (Geometry stage) Load the Step1X-3D-Geometry-1300m pipeline, run
       diffusion-guided occupancy field generation, extract a mesh via marching
       cubes, and export to GLB. Free GPU memory before proceeding.
    4. (Texture stage) Load the geometry GLB, clean degenerate faces and
       reduce face count, then run the Step1X-3D texture pipeline (SDXL +
       IG2MV adapter) to bake multi-view consistent textures.
    5. Write a provenance manifest via the atomic JSON writer.
    """
    args = parse_args()

    # Fail fast: confirm all weights and inputs are present before touching the GPU.
    validate_local_inputs(args.source, args.foreground_mask)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Canonical output paths for the two pipeline stages.
    geometry_path      = args.output_dir / "char_001_geometry.glb"
    textured_path      = args.output_dir / "char_001_textured.glb"
    intermediate_dir   = args.output_dir / "texture_intermediates"
    transparent_source = args.output_dir / "char_001_transparent_input.png"

    # ------------------------------------------------------------------
    # Pre-process: composite source image + foreground mask -> RGBA PNG
    # The geometry pipeline expects a transparent background so it can
    # correctly determine which voxels belong to the foreground subject.
    # ------------------------------------------------------------------
    source_image = Image.open(args.source).convert("RGB")

    # Resize the mask to match the source resolution using bilinear
    # interpolation, then use it as the alpha channel.
    alpha = Image.open(args.foreground_mask).convert("L").resize(
        source_image.size, Image.Resampling.BILINEAR
    )
    rgba = source_image.convert("RGBA")
    rgba.putalpha(alpha)
    rgba.save(transparent_source, format="PNG", optimize=True)

    # ------------------------------------------------------------------
    # Deferred heavy imports: PyTorch, trimesh, and the Step1X-3D source
    # packages are imported only after argument validation so that the
    # script fails fast on bad inputs without waiting for CUDA init.
    # ------------------------------------------------------------------
    sys.path.insert(0, str(STEP1X_CODE))
    import torch
    import trimesh
    from step1x3d_geometry.models.pipelines.pipeline import Step1X3DGeometryPipeline
    from step1x3d_geometry.models.pipelines.pipeline_utils import (
        reduce_face,
        remove_degenerate_face,
    )
    from step1x3d_texture.pipelines.step1x_3d_texture_synthesis_pipeline import (
        Step1X3DTextureConfig,
        Step1X3DTexturePipeline,
    )

    # ======================================================================
    # STAGE 1 - GEOMETRY
    # Diffusion-based occupancy field generation -> marching cubes -> GLB mesh
    # ======================================================================
    if args.stage in {"geometry", "all"}:
        geometry = Step1X3DGeometryPipeline.from_pretrained(
            STEP1X_MODEL,
            subfolder="Step1X-3D-Geometry-1300m",
            local_files_only=True,      # Enforce offline mode at the HF level too
            torch_dtype=torch.float16,  # fp16 cuts VRAM roughly in half vs fp32
        ).to("cuda")

        generator = torch.Generator(device=geometry.device).manual_seed(args.seed)

        output = geometry(
            str(transparent_source),

            # guidance_scale controls classifier-free guidance (CFG) strength.
            # Higher values push the output more strongly toward the image
            # condition, producing sharper geometry that closely follows the
            # reference silhouette at the cost of reduced diversity.
            # 8.0 is the value recommended in the Step1X-3D paper for
            # single-image-conditioned geometry generation.
            guidance_scale=8.0,

            num_inference_steps=args.geometry_steps,
            generator=generator,

            # The transparent_source already has the background removed via
            # the mask composite above, so we disable the pipeline's built-in
            # background removal to avoid double-processing.
            force_remove_background=False,

            # foreground_ratio controls how much of the image canvas the
            # subject occupies after the pipeline's internal centering/padding.
            # 0.95 means the character fills 95% of the canvas, leaving only
            # a 2.5% margin on each side.  A higher ratio produces denser
            # geometry near the image edges; lower values add more padding and
            # can cause the model to generate a smaller subject relative to the
            # bounding volume, reducing output mesh density.
            foreground_ratio=0.95,

            # octree_resolution sets the voxel grid resolution used for the
            # implicit occupancy field and the subsequent marching cubes
            # surface extraction.  384 means a 384^3 voxel grid (~56.6M cells).
            # Higher values (e.g. 512) yield finer surface detail and sharper
            # edges but require substantially more GPU memory and compute time.
            # 384 is the default recommended for 24 GB VRAM cards, balancing
            # mesh quality against memory headroom for the texture stage.
            # The marching cubes algorithm then extracts the isosurface at the
            # learned occupancy threshold, producing a watertight triangle mesh
            # whose resolution is bounded by this octree grid spacing.
            octree_resolution=384,

            # max_facenum caps the triangle count of the exported mesh.
            # 200,000 triangles is generous enough to preserve fine anime
            # costume details (buckles, ribbons, seams) while keeping the
            # GLB file size manageable and texture baking render time
            # within acceptable bounds.
            max_facenum=200000,
        )

        # Export the first (and only) mesh in the output list to GLB.
        output.mesh[0].export(geometry_path)

        # Release GPU memory explicitly before loading the texture pipeline.
        # The geometry transformer is large (~1.3B params); without this
        # cleanup the texture pipeline may OOM on 24 GB cards.
        del output, generator, geometry
        gc.collect()
        torch.cuda.empty_cache()

    # ======================================================================
    # STAGE 2 - TEXTURE
    # SDXL + IG2MV IP-Adapter multi-view texture baking -> textured GLB
    # ======================================================================
    if args.stage in {"texture", "all"}:
        if not geometry_path.is_file():
            raise FileNotFoundError(geometry_path)

        # Load the geometry and clean it before UV/texture baking.
        mesh = trimesh.load(geometry_path, force="mesh")

        # Remove zero-area triangles that would cause NaN gradients in the
        # rasteriser during texture baking.
        mesh = remove_degenerate_face(mesh)

        # Reduce the face count to the budget used during texture synthesis.
        # Fewer faces speed up the multi-view render passes inside the pipeline.
        mesh = reduce_face(mesh)

        # Build the texture pipeline configuration.
        # Parameters are set explicitly here (rather than relying on dataclass
        # defaults) so that the manifest records the exact values used and
        # the run is self-documenting even without consulting source code.
        config = Step1X3DTextureConfig()
        config.base_model  = str(SDXL_MODEL)                     # SDXL backbone
        config.vae_model   = str(SDXL_VAE)                       # fp16-safe VAE
        config.adapter_path = str(STEP1X_MODEL / "Step1X-3D-Texture")
        config.adapter_weight_name = "step1x-3d-ig2v.safetensors"  # IG2MV weights
        config.device = "cuda"
        config.dtype  = torch.float16                            # fp16 for VRAM savings

        config.num_inference_steps = args.texture_steps

        # guidance_scale for the texture diffusion stage.
        # Lower than the geometry stage (3.5 vs 8.0) because the texture
        # pipeline already has strong image conditioning from the IG2MV
        # IP-Adapter; too-high CFG causes over-saturation and colour
        # banding in multi-view-consistent texture baking.
        config.guidance_scale = 3.5

        # reference_conditioning_scale controls how strongly the IP-Adapter
        # injects colour/style from the reference image.  1.2 slightly
        # amplifies the adapter's influence above its unit weight (1.0),
        # helping preserve costume colours and line-art details from the
        # supervision reference.
        config.reference_conditioning_scale = 1.2

        # Positive prompt: steer the texture toward the target product type
        # (anime resin figure) and request fidelity to reference colours.
        config.text = "high quality 3D anime resin figure, exact reference colors and costume"

        # Negative prompt: suppress common artefacts seen in multi-view
        # texture synthesis (watermarks, wrong colours, face deformations).
        config.negative_prompt = (
            "watermark, text, logo, redesigned costume, missing accessory, wrong colors, "
            "deformed face, noisy, blurry, low detail"
        )

        # Resolution of each rendered view used during texture baking.
        config.render_size  = 1024
        # Resolution of the final baked UV texture atlas.
        config.texture_size = 1024
        # Sync the texture_size into the sub-config dict used by the
        # texture synthesis module (required by the pipeline internals).
        config.texture_sync_config["texture_size"] = 1024

        # Save per-iteration multi-view renders for debugging and QC review.
        config.save_intermediates = True
        config.intermediate_dir   = str(intermediate_dir)

        texture = Step1X3DTexturePipeline(config)

        # Enable VAE memory optimisations: slicing processes the batch one
        # image at a time; tiling decodes spatial tiles sequentially.
        # Both are required to stay within 24 GB VRAM with 1024^2 render views.
        texture.ig2mv_pipe.vae.enable_slicing()
        texture.ig2mv_pipe.vae.enable_tiling()

        # Run texture synthesis.  Use the original white-background source
        # (not the transparent composite) because the texture pipeline's
        # IP-Adapter performs its own background handling via remove_bg=False.
        textured_mesh = texture(str(args.source), mesh, remove_bg=False, seed=args.seed)
        textured_mesh.export(textured_path)

        # Free GPU memory.
        del textured_mesh, texture, mesh
        gc.collect()
        torch.cuda.empty_cache()

    # ------------------------------------------------------------------
    # Write provenance manifest (atomic, so readers never see partial JSON).
    # All hardcoded generation parameters are included alongside CLI args
    # so the manifest is a complete, self-contained record of how the
    # outputs were produced - no need to cross-reference source code.
    # ------------------------------------------------------------------
    manifest = {
        "created_at": datetime.now(timezone.utc).astimezone().isoformat(),
        "provider": "server_local_step1x3d_offline",
        "source": str(args.source.resolve()),
        "source_sha256": sha256(args.source),
        "foreground_mask": str(args.foreground_mask.resolve()),
        "foreground_mask_sha256": sha256(args.foreground_mask),
        "transparent_geometry_input": str(transparent_source.resolve()),
        "transparent_geometry_input_sha256": sha256(transparent_source),
        "stage": args.stage,
        "models": {
            "step1x": str(STEP1X_MODEL.resolve()),
            "step1x_revision": STEP1X_MODEL.name,   # snapshot hash for reproducibility
            "sdxl":            str(SDXL_MODEL.resolve()),
            "sdxl_vae":        str(SDXL_VAE.resolve()),
        },
        "settings": {
            "geometry_steps":              args.geometry_steps,
            "texture_steps":               args.texture_steps,
            "seed":                        args.seed,
            # Record hardcoded generation parameters alongside CLI arguments
            # so the manifest is a complete record of how outputs were produced.
            "octree_resolution":           384,
            "max_facenum":                 200000,
            "texture_size":                1024,
            "render_size":                 1024,
            "reference_conditioning_scale": 1.2,
        },
        "geometry":        str(geometry_path.resolve()) if geometry_path.is_file() else None,
        "geometry_sha256": sha256(geometry_path) if geometry_path.is_file() else None,
        "textured":        str(textured_path.resolve()) if textured_path.is_file() else None,
        "textured_sha256": sha256(textured_path) if textured_path.is_file() else None,
        "intermediates":   str(intermediate_dir.resolve()),
        "network_policy":  "offline_local_files_only",
        "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES"),
    }
    atomic_json(args.output_dir / "manifest.json", manifest)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
